services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: always
    ports:
      - '80:80'                       # Public HTTP Port
      - '443:443'                     # Public HTTPS Port
      - '81:81'                       # Admin Web Port
    env_file:
      - npm.env
    environment:
      DB_MYSQL_HOST: "npm-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "${DB_MYSQL_USER:-npm}"
      DB_MYSQL_PASSWORD: "${DB_MYSQL_PASSWORD:-npm}"
      DB_MYSQL_NAME: "npm"
      DISABLE_IPV6: 'true'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    depends_on:
      - npm-db

  npm-db:
    image: 'mariadb:latest'
    container_name: npm-db
    restart: always
    env_file:
      - npm.env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-npm}"
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: "${MYSQL_USER:-npm}"git config --local user.name
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-npm}"
    volumes:
      - ./npm/mysql:/var/lib/mysql
